# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group', models.CharField(blank=True, help_text='Name of an experiment group, task, or other specific item.', max_length=256, null=True)),
                ('time', models.DateField(default=datetime.date.today)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set([('name', 'group', 'time')]),
        ),
    ]
