# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
