// fetching actions
export const FETCH_STATIC_DATA = 'FETCH_STATIC_DATA';
export const FETCH_STATIC_DATA_FULFILLED = 'FETCH_STATIC_DATA_FULFILLED';
export const FETCH_PRACTICE_OVERVIEW = 'FETCH_PRACTICE_OVERVIEW';
export const FETCH_PRACTICE_OVERVIEW_PENDING = 'FETCH_PRACTICE_OVERVIEW_PENDING';
export const FETCH_PRACTICE_OVERVIEW_FULFILLED = 'FETCH_PRACTICE_OVERVIEW_FULFILLED';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_FULFILLED = 'UPDATE_STUDENT_FULFILLED';

// reporting actions
export const START_SESSION = 'START_SESSION';
export const START_SESSION_FULFILLED = 'START_SESSION_FULFILLED';
export const START_TASK = 'START_TASK';
export const START_TASK_FULFILLED = 'START_TASK_FULFILLED';
export const SOLVE_TASK = 'SOLVE_TASK';
export const SOLVE_TASK_FULFILLED = 'SOLVE_TASK_FULFILLED';
export const SEE_INSTRUCTION = 'SEE_INSTRUCTION';
export const SEE_INSTRUCTION_PENDING = 'SEE_INSTRUCTION_PENDING';
export const SEE_INSTRUCTION_FULFILLED = 'SEE_INSTRUCTION_FULFILLED';
export const REPORT_PROGRAM_EDIT = 'REPORT_PROGRAM_EDIT';
export const REPORT_PROGRAM_EDIT_FULFILLED = 'REPORT_PROGRAM_EDIT_FULFILLED';
export const REPORT_PROGRAM_EDIT_PENDING = 'REPORT_PROGRAM_EDIT_PENDING';

export const CREATE_TASK_ENVIRONMENT = 'CREATE_TASK_ENVIRONMENT';
export const SET_TASK = 'SET_TASK';
export const SET_TASK_SESSION = 'SET_TASK_SESSION';
export const CHANGE_SETTING = 'CHANGE_SETTING';
export const CHANGE_CODE = 'CHANGE_CODE';
export const CHANGE_ROBO_AST = 'CHANGE_ROBO_AST';
export const RESET_GAME = 'RESET_GAME';
export const DO_ACTION = 'DO_ACTION';
export const MOVE = 'MOVE';
export const EVOLVE_WORLD = 'EVOLVE_WORLD';
export const INTERPRETATION_STARTED = 'INTERPRETATION_STARTED';
export const INTERPRETATION_FINISHED = 'INTERPRETATION_FINISHED';
export const CHANGE_GAME_PANEL_WIDTH = 'CHANGE_GAME_PANEL_WIDTH';
export const SET_EDITOR_TYPE = 'SET_EDITOR_TYPE';
export const SWITCH_VIM_MODE = 'SWITCH_VIM_MODE';
export const SHOW_INSTRUCTIONS = 'SHOW_INSTRUCTIONS';
export const SET_STUDENT = 'SET_STUDENT';
export const CLOSE_TASK_COMPLETION_DIALOG = 'CLOSE_TASK_COMPLETION_DIALOG';
export const SHOW_NEXT_LEVEL_STATUS = 'SHOW_NEXT_LEVEL_STATUS';
