//const REQUEST = 'REQUEST'
//const SUCCESS = 'SUCCESS'
//const FAILURE = 'FAILURE'
//
//function createRequestTypes(base) {
//  return [REQUEST, SUCCESS, FAILURE].reduce((acc, type) => {
//		acc[type] = `${base}_${type}`
//		return acc
//	}, {})
//}
//
//export const FETCH_WORLD = createRequestTypes('FETCH_WORLD')
//export const FETCH_USER = createRequestTypes('FETCH_USER')
//export const FETCH_STUDENT = createRequestTypes('FETCH_STUDENT')
//export const FETCH_PRACTICE_OVERVIEW = createRequestTypes('FETCH_PRACTICE_OVERVIEW')

export const FETCH_API_ROOT_REQUEST = 'FETCH_API_ROOT_REQUEST';
export const FETCH_API_ROOT_SUCCESS = 'FETCH_API_ROOT_SUCCESS';
export const FETCH_API_ROOT_FAILURE = 'FETCH_API_ROOT_FAILURE';

export const FETCH_WORLD_REQUEST = 'FETCH_WORLD_REQUEST';
export const FETCH_WORLD_SUCCESS = 'FETCH_WORLD_SUCCESS';
export const FETCH_WORLD_FAILURE = 'FETCH_WORLD_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE';

export const FETCH_PRACTICE_OVERVIEW_REQUEST = 'FETCH_PRACTICE_OVERVIEW_REQUEST'
export const FETCH_PRACTICE_OVERVIEW_SUCCESS = 'FETCH_PRACTICE_OVERVIEW_SUCCESS'
export const FETCH_PRACTICE_OVERVIEW_FAILURE = 'FETCH_PRACTICE_OVERVIEW_FAILURE'

export const CREATE_TASK_ENVIRONMENT = 'CREATE_TASK_ENVIRONMENT';
export const SET_TASK = 'SET_TASK';
export const SET_TASK_BY_ID = 'SET_TASK_BY_ID';

export const START_TASK_REQUEST = 'START_TASK_REQUEST';
export const START_TASK_SUCCESS = 'START_TASK_SUCCESS';
export const START_TASK_FAILURE = 'START_TASK_FAILURE';

export const SEE_INSTRUCTION_REQUEST = 'SEE_INSTRUCTION_REQUEST';
export const SEE_INSTRUCTION_SUCCESS = 'SEE_INSTRUCTION_SUCCESS';
export const SEE_INSTRUCTION_FAILURE = 'SEE_INSTRUCTION_FAILURE';

export const EDIT_PROGRAM_AST = 'EDIT_PROGRAM_AST';
export const EDIT_PROGRAM_CODE = 'EDIT_PROGRAM_CODE';

export const RUN_PROGRAM_START = 'RUN_PROGRAM_START';
//export const RUN_PROGRAM_SOLVED = 'RUN_PROGRAM_SOLVED';
export const RUN_PROGRAM_SOLVED_REPORT = 'RUN_PROGRAM_SOLVED_REPORT';


export const INTERPRETATION_STARTED = 'INTERPRETATION_STARTED';
export const INTERPRETATION_FINISHED = 'INTERPRETATION_FINISHED';
export const RESET_GAME = 'RESET_GAME';
export const DO_ACTION_MOVE = 'DO_ACTION_MOVE';
export const DO_ACTION = 'DO_ACTION';
export const MOVE = 'MOVE';
export const EVOLVE_WORLD = 'EVOLVE_WORLD';

export const CHANGE_SETTING = 'CHANGE_SETTING';
export const CHANGE_GAME_PANEL_WIDTH = 'CHANGE_GAME_PANEL_WIDTH';
export const SET_EDITOR_TYPE = 'SET_EDITOR_TYPE';
export const SWITCH_VIM_MODE = 'SWITCH_VIM_MODE';
export const SHOW_INSTRUCTIONS = 'SHOW_INSTRUCTIONS';
export const CLOSE_TASK_COMPLETION_DIALOG = 'CLOSE_TASK_COMPLETION_DIALOG';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const EXPORT_TASK = 'EXPORT_TASK';
export const IMPORT_TASK = 'IMPORT_TASK';

export const SHOW_LEVEL_PROGRESS_START = 'SHOW_LEVEL_PROGRESS_START';
export const SHOW_NEXT_LEVEL_STATUS = 'SHOW_NEXT_LEVEL_STATUS';
