# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_student_toolbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('name', models.SlugField(unique=True)),
                ('credits', models.IntegerField(help_text='Number of credits needed to complete this level.')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Toolbox')),
            ],
        ),
    ]
