# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('setting', jsonfield.fields.JSONField()),
                ('solution', jsonfield.fields.JSONField()),
                ('level', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learn.Level')),
            ],
        ),
    ]
