# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_data_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('end', models.DateTimeField(default=datetime.datetime.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sessions', to='learn.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Task')),
            ],
        ),
    ]
