# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_tasksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seen_instructions',
            field=models.ManyToManyField(to='learn.Instruction'),
        ),
    ]
