# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_student_seen_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learn.Task'),
        ),
    ]
