# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_programsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('start-task', 'start-task'), ('edit-program', 'edit-program'), ('run-program', 'run-program'), ('watch-instruction', 'watch-instruction')], help_text='One of the predefined types of actions.', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('randomness', models.IntegerField(default=learn.models.generate_random_integer)),
                ('data', jsonfield.fields.JSONField(help_text='Unstructured part of the data (depends on the action type).')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Student')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Task')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
