# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_tasksession_start_end_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(),
        ),
    ]
