# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 15:23
from __future__ import unicode_literals

from django.db import migrations


def create_initial_user_student(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Student = apps.get_model('learn', 'Student')
    User.objects.filter(username='initial').delete()
    user = User.objects.create(username='initial')
    Student.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_teacher_classroom'),
    ]

    operations = [
        migrations.RunPython(create_initial_user_student),
    ]
