# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0019_initial_user_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level']},
        ),
    ]
