# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0022_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksession',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksession',
            name='performance',
            field=models.SmallIntegerField(choices=[(0, 'unsolved'), (1, 'poor'), (2, 'good'), (3, 'excellent')], default=0),
        ),
    ]
