# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_tasksession_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Chunk')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learn.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('student', 'chunk')]),
        ),
    ]
