# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0025_chunk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsnapshot',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
