# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_programsnapshot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('order', models.SmallIntegerField(unique=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learn.Chunk')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Toolbox')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
