# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0027_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='subchunks',
            field=models.ManyToManyField(related_name='parents', to='learn.Chunk'),
        ),
    ]
