# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 13:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0028_chunk_subchunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='toolbox',
        ),
        migrations.AddField(
            model_name='chunk',
            name='setting',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
