# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0029_chunk_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
