# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0030_mission_order_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default=learn.models.generate_uuid_string, unique=True)),
                ('blocks', models.ManyToManyField(to='learn.Block')),
                ('chunks', models.ManyToManyField(to='learn.Chunk')),
                ('missions', models.ManyToManyField(to='learn.Mission')),
                ('tasks', models.ManyToManyField(to='learn.Task')),
                ('toolboxes', models.ManyToManyField(to='learn.Toolbox')),
            ],
        ),
    ]
