# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0031_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='level',
        ),
        migrations.AlterField(
            model_name='chunk',
            name='tasks',
            field=models.ManyToManyField(related_name='chunks', to='learn.Task'),
        ),
    ]
