# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0032_remove_task_level_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='toolbox',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
