# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0034_default_skill_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('value', models.FloatField(default=0)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Chunk')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='learn.Domain')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Task')),
            ],
        ),
    ]
