# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_problemsets2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='level',
            field=models.SmallIntegerField(default=0, help_text='The top-most section number.'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='section',
            field=models.CharField(blank=True, default='', help_text="Dot-numbering '<mission>.<phase>', e.g. '3.4'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='setting',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='setting',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
