# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0038_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chunk_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Chunk'),
        ),
    ]
