# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 06:28
from __future__ import unicode_literals

from django.db import migrations

def create_parent_chunks(apps, schema_editor):
    Task = apps.get_model('learn', 'Task')
    Chunk = apps.get_model('learn', 'Chunk')
    Chunk.objects.all().delete()
    for task in Task.objects.all():
        chunk = Chunk.objects.create(id=task.pk, name=task.name, order=task.order)
        task.chunk_ptr = chunk  # chunk.pk
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0039_task_chunk_ptr'),
    ]

    operations = [
        migrations.RunPython(create_parent_chunks),
    ]
