# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0040_task_chunk_ptr_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AlterField(
            model_name='task',
            name='chunk_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='task_obj', serialize=False, to='learn.Chunk'),
        ),
    ]
