# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0041_task_chunk_inheritance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['section']},
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='order',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='level',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='section',
        ),
        migrations.AddField(
            model_name='chunk',
            name='section',
            field=models.CharField(blank=True, default='', help_text="Dotted section e.g. '3.4'.", max_length=20),
        ),
    ]
