# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 07:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0042_chunk_section_level_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='task',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
        migrations.AddField(
            model_name='chunk',
            name='content',
            field=jsonfield.fields.JSONField(default=dict, help_text='Description, setting, solution, etc.'),
        ),
    ]
