# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0043_chunk_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
