# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0044_chunk_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['type', 'section']},
        ),
    ]
