# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0045_chunk_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='section',
            field=models.CharField(blank=True, default='0', help_text="Dotted section e.g. '3.4'.", max_length=20),
        ),
    ]
