# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0046_chunk_section_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='granularity',
            field=models.CharField(choices=[('mission', 'mission'), ('phase', 'phase')], default='mission', help_text='Hierachy level; either base phase, or compound mission.', max_length=10),
        ),
    ]
