# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0047_problemset_granularity_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemset',
            options={'base_manager_name': 'objects'},
        ),
    ]
