# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0053_instruction_chunk_inheritance'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='instructions',
            field=models.ManyToManyField(to='learn.Instruction'),
        ),
    ]
