# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0055_data_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsnapshot',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Order of the snapshot for given task session and granularity.', null=True),
        ),
        migrations.AddField(
            model_name='programsnapshot',
            name='time_from_start',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number of seconds from the start of the task session.', null=True),
        ),
        migrations.AlterField(
            model_name='programsnapshot',
            name='correct',
            field=models.NullBooleanField(default=None, help_text='Whether the snapshot is correct solution (executions only).'),
        ),
    ]
