# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0056_snapshots_order_time_from_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programsnapshot',
            options={'ordering': ['time']},
        ),
    ]
