# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0057_snapshots_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsnapshot',
            name='time_delta',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Number of seconds from the last snapshot of the same granularity.', null=True),
        ),
    ]
